<?php

namespace app\forms;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class CenterForm extends Model
{
	public $id;
    public $city;
    public $count;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
           [['city', 'count'], 'required'],
        ];
    }
	/**
	 * @return array customized attribute labels
	 */
	public function attributes()
	{
		return['id','city','count']; // TODO: Change the autogenerated stub
	}

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
			'id' => 'id',
            'city' => 'Склад',
			'count' => 'Количество',
        ];
    }


}
